### ISSUE TITLE
Build failure Ubuntu 14.04 64-bit - org/apache/commons/lang/StringUtils not found?

### ISSUE THREAD

**Issue by beenhead** [mesos/chronos#211]
Hello - I had the original release up and running, with zookeeper, mesos etc. - now trying to get on current version. Having some trouble compiling:

```
java -version
java version "1.7.0_51"
OpenJDK Runtime Environment (IcedTea 2.4.6) (7u51-2.4.6-1ubuntu4)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```

```
mvn -X clean package
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-19-generic", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /root/.m2/settings.xml
[DEBUG] Using local repository at /root/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /root/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.airbnb:chronos:jar:2.1.0_mesos-0.14.0-rc4: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.airbnb:chronos:jar:2.1.0_mesos-0.14.0-rc4
[DEBUG] Tasks:   [clean, package]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building chronos 2.1.0_mesos-0.14.0-rc4
[INFO] ------------------------------------------------------------------------
```

snip

```
[INFO] Add Source directory: /usr/local/chronos/src/main/scala
[INFO] Add Test Source directory: /usr/local/chronos/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ chronos ---
[DEBUG] Configuring mojo net.alchim31.maven:scala-maven-plugin:3.1.0:compile from plugin realm ClassRealm[plugin>net.alchim31.maven:scala-maven-plugin:3.1.0, parent: sun.misc.Launcher$AppClassLoader@4ecac02f]
[DEBUG] Configuring mojo 'net.alchim31.maven:scala-maven-plugin:3.1.0:compile' with basic configurator -->
[DEBUG]   (f) analysisCacheFile = /usr/local/chronos/target/analysis/compile
[DEBUG]   (f) args = [-unchecked, -deprecation, -encoding, utf8]
[DEBUG]   (f) checkMultipleScalaVersions = true
[DEBUG]   (f) compileOrder = mixed
[DEBUG]   (f) displayCmd = false
[DEBUG]   (f) failOnMultipleScalaVersions = false
[DEBUG]   (f) forceUseArgFile = false
[DEBUG]   (f) fork = true
[DEBUG]   (f) javacArgs = []
[DEBUG]   (f) jvmArgs = [-Xmx2G]
[DEBUG]   (f) localRepo =        id: local
      url: file:///root/.m2/repository/
   layout: none

[DEBUG]   (f) localRepository =        id: local
      url: file:///root/.m2/repository/
   layout: none

[DEBUG]   (f) notifyCompilation = true
[DEBUG]   (f) outputDir = /usr/local/chronos/target/classes
[DEBUG]   (f) pluginArtifacts = [net.alchim31.maven:scala-maven-plugin:maven-plugin:3.1.0:, org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile, org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile, org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile, org.sonatype.aether:aether-util:jar:1.7:compile, org.codehaus.plexus:plexus-interpolation:jar:1.14:compile, org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile, org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile, org.sonatype.plexus:plexus-cipher:jar:1.4:compile, org.apache.maven.shared:maven-dependency-tree:jar:1.2:compile, org.apache.commons:commons-exec:jar:1.0.1:compile, org.codehaus.plexus:plexus-utils:jar:3.0:compile, org.codehaus.plexus:plexus-archiver:jar:2.1:compile, junit:junit:jar:3.8.1:compile, org.codehaus.plexus:plexus-io:jar:2.0.2:compile, org.apache.maven.doxia:doxia-sink-api:jar:1.1.2:compile, org.apache.maven.doxia:doxia-logging-api:jar:1.1.2:compile, org.codehaus.jackson:jackson-core-asl:jar:1.6.1:compile, org.codehaus.jackson:jackson-mapper-asl:jar:1.6.1:compile, org.apache.maven.shared:maven-invoker:jar:2.0.11:compile, org.apache.maven:maven-archiver:jar:2.5:compile, com.typesafe.zinc:zinc:jar:0.1.0:compile, org.scala-lang:scala-library:jar:2.9.2:compile, com.typesafe.sbt:incremental-compiler:jar:0.12.0:compile, com.typesafe.sbt:sbt-interface:jar:0.12.0:compile, org.scala-lang:scala-compiler:jar:2.9.2:compile, com.typesafe.sbt:compiler-interface:jar:sources:0.12.0:compile]
[DEBUG]   (f) project = MavenProject: com.airbnb:chronos:2.1.0_mesos-0.14.0-rc4 @ /usr/local/chronos/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: com.airbnb:chronos:2.1.0_mesos-0.14.0-rc4 @ /usr/local/chronos/pom.xml]
[DEBUG]   (f) recompileMode = all
[DEBUG]   (f) remoteRepos = [       id: twitter-repo
      url: http://maven.twttr.com/
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: mesosphere-public-repo
      url: http://downloads.mesosphere.io/maven
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: libs-folder
      url: file:///usr/local/chronos/lib
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: central
      url: http://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG]   (f) scalaClassName = scala.tools.nsc.Main
[DEBUG]   (f) scalaVersion = 2.10.3
[DEBUG]   (f) sendJavaToScalac = true
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@62507110
[DEBUG]   (f) sourceDir = /usr/local/chronos/src/main/java/../scala
[DEBUG]   (f) useCanonicalPath = true
[DEBUG]   (f) useZincServer = false
[DEBUG]   (f) zincPort = 3030
[DEBUG] -- end configuration --
[DEBUG] Checking for multiple versions of scala
[DEBUG] Dependency tree resolution listener events:
[DEBUG] testArtifact: artifact=com.airbnb:chronos:jar:2.1.0_mesos-0.14.0-rc4
[DEBUG] includeArtifact: artifact=com.airbnb:chronos:jar:2.1.0_mesos-0.14.0-rc4
[DEBUG] startProcessChildren: artifact=com.airbnb:chronos:jar:2.1.0_mesos-0.14.0-rc4
[DEBUG]   testArtifact: artifact=org.scala-lang:scala-library:jar:2.10.3:compile
[DEBUG]   includeArtifact: artifact=org.scala-lang:scala-library:jar:2.10.3:compile
[DEBUG]   startProcessChildren: artifact=org.scala-lang:scala-library:jar:2.10.3:compile
[DEBUG]   endProcessChildren: artifact=org.scala-lang:scala-library:jar:2.10.3:compile
[DEBUG] Verifying availability of /root/.m2/repository/org/apache/apache/11/apache-11.pom from [twitter-repo (http://maven.twttr.com/, releases+snapshots), mesosphere-public-repo (http://downloads.mesosphere.io/maven, releases+snapshots), libs-folder (file:///usr/local/chronos/lib, releases+snapshots), central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for http://downloads.mesosphere.io/maven via ussocinfra01:3128 as null
Downloading: http://downloads.mesosphere.io/maven/org/apache/apache/11/apache-11.pom
[DEBUG] Writing resolution tracking file /root/.m2/repository/org/apache/apache/11/apache-11.pom.lastUpdated
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for file:///usr/local/chronos/lib
Downloading: file:///usr/local/chronos/lib/org/apache/apache/11/apache-11.pom
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
        at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.889s
[INFO] Finished at: Mon Apr 28 14:53:43 UTC 2014
[INFO] Final Memory: 20M/965M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project chronos: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile failed: A required class was missing while executing net.alchim31.maven:scala-maven-plugin:3.1.0:compile: org/apache/commons/lang/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:3.1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.1.0/scala-maven-plugin-3.1.0.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[4] = file:/root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/root/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
[ERROR] urls[10] = file:/root/.m2/repository/org/apache/commons/commons-exec/1.0.1/commons-exec-1.0.1.jar
[ERROR] urls[11] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[ERROR] urls[12] = file:/root/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
[ERROR] urls[13] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[14] = file:/root/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
[ERROR] urls[15] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
[ERROR] urls[16] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
[ERROR] urls[17] = file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.6.1/jackson-core-asl-1.6.1.jar
[ERROR] urls[18] = file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.6.1/jackson-mapper-asl-1.6.1.jar
[ERROR] urls[19] = file:/root/.m2/repository/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
[ERROR] urls[20] = file:/root/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
[ERROR] urls[21] = file:/root/.m2/repository/com/typesafe/zinc/zinc/0.1.0/zinc-0.1.0.jar
[ERROR] urls[22] = file:/root/.m2/repository/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar
[ERROR] urls[23] = file:/root/.m2/repository/com/typesafe/sbt/incremental-compiler/0.12.0/incremental-compiler-0.12.0.jar
[ERROR] urls[24] = file:/root/.m2/repository/com/typesafe/sbt/sbt-interface/0.12.0/sbt-interface-0.12.0.jar
[ERROR] urls[25] = file:/root/.m2/repository/org/scala-lang/scala-compiler/2.9.2/scala-compiler-2.9.2.jar
[ERROR] urls[26] = file:/root/.m2/repository/com/typesafe/sbt/compiler-interface/0.12.0/compiler-interface-0.12.0-sources.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.apache.commons.lang.StringUtils
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project chronos: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile failed: A required class was missing while executing net.alchim31.maven:scala-maven-plugin:3.1.0:compile: org/apache/commons/lang/StringUtils
-----------------------------------------------------
realm =    plugin>net.alchim31.maven:scala-maven-plugin:3.1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/root/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.1.0/scala-maven-plugin-3.1.0.jar
urls[1] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
urls[4] = file:/root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/root/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
urls[10] = file:/root/.m2/repository/org/apache/commons/commons-exec/1.0.1/commons-exec-1.0.1.jar
urls[11] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
urls[12] = file:/root/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
urls[13] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[14] = file:/root/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
urls[15] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
urls[16] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
urls[17] = file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.6.1/jackson-core-asl-1.6.1.jar
urls[18] = file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.6.1/jackson-mapper-asl-1.6.1.jar
urls[19] = file:/root/.m2/repository/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
urls[20] = file:/root/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
urls[21] = file:/root/.m2/repository/com/typesafe/zinc/zinc/0.1.0/zinc-0.1.0.jar
urls[22] = file:/root/.m2/repository/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar
urls[23] = file:/root/.m2/repository/com/typesafe/sbt/incremental-compiler/0.12.0/incremental-compiler-0.12.0.jar
urls[24] = file:/root/.m2/repository/com/typesafe/sbt/sbt-interface/0.12.0/sbt-interface-0.12.0.jar
urls[25] = file:/root/.m2/repository/org/scala-lang/scala-compiler/2.9.2/scala-compiler-2.9.2.jar
urls[26] = file:/root/.m2/repository/com/typesafe/sbt/compiler-interface/0.12.0/compiler-interface-0.12.0-sources.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile failed: A required class was missing while executing net.alchim31.maven:scala-maven-plugin:3.1.0:compile: org/apache/commons/lang/StringUtils
-----------------------------------------------------
realm =    plugin>net.alchim31.maven:scala-maven-plugin:3.1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/root/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.1.0/scala-maven-plugin-3.1.0.jar
urls[1] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
urls[4] = file:/root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/root/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
urls[10] = file:/root/.m2/repository/org/apache/commons/commons-exec/1.0.1/commons-exec-1.0.1.jar
urls[11] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
urls[12] = file:/root/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
urls[13] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[14] = file:/root/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
urls[15] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
urls[16] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
urls[17] = file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.6.1/jackson-core-asl-1.6.1.jar
urls[18] = file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.6.1/jackson-mapper-asl-1.6.1.jar
urls[19] = file:/root/.m2/repository/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
urls[20] = file:/root/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
urls[21] = file:/root/.m2/repository/com/typesafe/zinc/zinc/0.1.0/zinc-0.1.0.jar
urls[22] = file:/root/.m2/repository/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar
urls[23] = file:/root/.m2/repository/com/typesafe/sbt/incremental-compiler/0.12.0/incremental-compiler-0.12.0.jar
urls[24] = file:/root/.m2/repository/com/typesafe/sbt/sbt-interface/0.12.0/sbt-interface-0.12.0.jar
urls[25] = file:/root/.m2/repository/org/scala-lang/scala-compiler/2.9.2/scala-compiler-2.9.2.jar
urls[26] = file:/root/.m2/repository/com/typesafe/sbt/compiler-interface/0.12.0/compiler-interface-0.12.0-sources.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing net.alchim31.maven:scala-maven-plugin:3.1.0:compile: org/apache/commons/lang/StringUtils
-----------------------------------------------------
realm =    plugin>net.alchim31.maven:scala-maven-plugin:3.1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/root/.m2/repository/net/alchim31/maven/scala-maven-plugin/3.1.0/scala-maven-plugin-3.1.0.jar
urls[1] = file:/root/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/root/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/root/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
urls[4] = file:/root/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[5] = file:/root/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/root/.m2/repository/org/apache/maven/shared/maven-dependency-tree/1.2/maven-dependency-tree-1.2.jar
urls[10] = file:/root/.m2/repository/org/apache/commons/commons-exec/1.0.1/commons-exec-1.0.1.jar
urls[11] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
urls[12] = file:/root/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1/plexus-archiver-2.1.jar
urls[13] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[14] = file:/root/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
urls[15] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
urls[16] = file:/root/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
urls[17] = file:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.6.1/jackson-core-asl-1.6.1.jar
urls[18] = file:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.6.1/jackson-mapper-asl-1.6.1.jar
urls[19] = file:/root/.m2/repository/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
urls[20] = file:/root/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
urls[21] = file:/root/.m2/repository/com/typesafe/zinc/zinc/0.1.0/zinc-0.1.0.jar
urls[22] = file:/root/.m2/repository/org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar
urls[23] = file:/root/.m2/repository/com/typesafe/sbt/incremental-compiler/0.12.0/incremental-compiler-0.12.0.jar
urls[24] = file:/root/.m2/repository/com/typesafe/sbt/sbt-interface/0.12.0/sbt-interface-0.12.0.jar
urls[25] = file:/root/.m2/repository/org/scala-lang/scala-compiler/2.9.2/scala-compiler-2.9.2.jar
urls[26] = file:/root/.m2/repository/com/typesafe/sbt/compiler-interface/0.12.0/compiler-interface-0.12.0-sources.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:125)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at org.apache.maven.wagon.providers.file.FileWagon.resolveDestinationPath(FileWagon.java:206)
        at org.apache.maven.wagon.providers.file.FileWagon.resourceExists(FileWagon.java:265)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 7 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

Any ideas? Thanks :)

**Comment by arichiardi** [comment]
The simlink solves here too!

**Comment by kxtMy** [comment]
When I use Maven of Eclipse(Windows10 OS) deploy to tomcat of Ubuntu 15.10,I meet the same prolem,Can anyone tell me how to slove it,Please!!!

**Comment by kxtMy** [comment]
![image](https://user-images.githubusercontent.com/16443007/29545010-6a1c041e-871e-11e7-88ca-76fc6f0790dd.png)
