### ISSUE TITLE
can not run program "node "

### ISSUE THREAD

**Issue by kaybinwong** [mesos/chronos#276]
hi ,there,when i use the command "mvn -X clean package" to package the project,it shows the erros below,it makes me confused for a few days.can u help me?

ERROR:
Setting ro project property: ant.project.invoked-targets -> -optimize
Build sequence for target(s) `-optimize' is [-optimize]
Complete build sequence is [-optimize, sourceDir.check, assets.uptodate, generateAssets, ]

-optimize:
     [exec] Current OS is Linux
     [exec] Executing 'node' with arguments:
     [exec] '/home/intexh/git/chronos/src/main/resources/assets/r.js'
     [exec] '-o'
     [exec] '/home/intexh/git/chronos/src/main/resources/assets/app.build.js'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing 'node' with arguments:
'/home/intexh/git/chronos/src/main/resources/assets/r.js'
'-o'
'/home/intexh/git/chronos/src/main/resources/assets/app.build.js'

The ' characters around the executable and arguments are
not part of the command.
  [antcall] Exiting /home/intexh/git/chronos/build.xml.
      [ant] Exiting /home/intexh/git/chronos/build.xml.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.599 s
[INFO] Finished at: 2014-10-09T14:32:51+08:00
[INFO] Final Memory: 13M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (ant-run-requirejs) on project chronos: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/intexh/git/chronos/build.xml:26: The following error occurred while executing this line:
[ERROR] /home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
[ERROR] around Ant part ...<ant antfile="/home/intexh/git/chronos/build.xml">... @ 9:53 in /home/intexh/git/chronos/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (ant-run-requirejs) on project chronos: An Ant BuildException has occured: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:26: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
around Ant part ...<ant antfile="/home/intexh/git/chronos/build.xml">... @ 9:53 in /home/intexh/git/chronos/target/antrun/build-main.xml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:26: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
around Ant part ...<ant antfile="/home/intexh/git/chronos/build.xml">... @ 9:53 in /home/intexh/git/chronos/target/antrun/build-main.xml
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:355)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: /home/intexh/git/chronos/target/antrun/build-main.xml:9: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:26: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:444)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:327)
	... 21 more
Caused by: /home/intexh/git/chronos/build.xml:26: The following error occurred while executing this line:
/home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:444)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	... 33 more
Caused by: /home/intexh/git/chronos/build.xml:5: Execute failed: java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:675)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	... 47 more
Caused by: java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
	... 61 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 67 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by elingg** [comment]
node.js is a prereq. Closing the issue.

**Comment by alartin** [comment]
Absolutely node is a prereq, but I did not know it until this error occured. Unfortunately, there is not prereq section in the README file.

**Comment by alartin** [comment]
BTW, I suggest to add a task in the build.xml if there is no node installed and install it automatically.
