### ISSUE TITLE
Command is required for docker containers

### ISSUE THREAD

**Issue by bobrik** [mesos/chronos#544]
You can live without setting explicit `command` for docker containers. For some reason, Chronos disagrees with `500 Internal Server Error`:

```
Sep  1 11:05:14 36com15 docker[18501]: [2015-09-01 11:05:14,871] ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container (com.sun.jersey.spi.container.ContainerResponse:419)
Sep  1 11:05:14 36com15 docker[18501]: java.lang.NullPointerException
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:32)
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:24)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)
Sep  1 11:05:14 36com15 docker[18501]: at mesosphere.chaos.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:59)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:86)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:203)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
Sep  1 11:05:14 36com15 docker[18501]: at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
Sep  1 11:05:14 36com15 docker[18501]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.scheduler.api.RedirectFilter.doFilter(RedirectFilter.scala:33)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Sep  1 11:05:14 36com15 docker[18501]: at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.Server.handle(Server.java:370)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Sep  1 11:05:14 36com15 docker[18501]: at java.lang.Thread.run(Thread.java:745)
Sep  1 11:05:14 36com15 docker[18501]: [2015-09-01 11:05:14,871] WARN /scheduler/iso8601 (org.eclipse.jetty.servlet.ServletHandler:563)
Sep  1 11:05:14 36com15 docker[18501]: java.lang.NullPointerException
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:32)
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:24)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
Sep  1 11:05:14 36com15 docker[18501]: at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)
Sep  1 11:05:14 36com15 docker[18501]: at mesosphere.chaos.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:59)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:86)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:203)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
Sep  1 11:05:14 36com15 docker[18501]: at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
Sep  1 11:05:14 36com15 docker[18501]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
Sep  1 11:05:14 36com15 docker[18501]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
Sep  1 11:05:14 36com15 docker[18501]: at org.apache.mesos.chronos.scheduler.api.RedirectFilter.doFilter(RedirectFilter.scala:33)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Sep  1 11:05:14 36com15 docker[18501]: at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Sep  1 11:05:14 36com15 docker[18501]: at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.Server.handle(Server.java:370)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Sep  1 11:05:14 36com15 docker[18501]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Sep  1 11:05:14 36com15 docker[18501]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by elison** [comment]
Looking at the definition in BaseJob it seems like name and command both have to be specified as they have no default value.

**Comment by ddossot** [comment]
This is still broken.

If you omit the `command` property from the job JSON entity you post, you get this:

<pre>[2016-03-16 16:20:13,336] ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container (com.sun.jersey.spi.container.ContainerResponse:419)
java.lang.NullPointerException
	at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:32)
	at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:24)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)
	at mesosphere.chaos.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:59)
	at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
	at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
	at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:86)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:203)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at org.apache.mesos.chronos.scheduler.api.RedirectFilter.doFilter(RedirectFilter.scala:34)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)</pre>

This is because of this [LOC](https://github.com/mesos/chronos/blob/fc2567dbfb0567fd35a496be09a39474c3d0a7c6/src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala#L32):

    val command = node.get("command").asText

which assumes that the `command` property is always present, although it is not required for Docker jobs.

**Comment by rphull** [comment]
**1. Problems with Mandatory Command Field:**

Job definition as follows:
{
  "schedule": "R0//P",
  "name": "testjob",
  "container": {
    "type": "DOCKER",
    "image": "path_to_image",
    "network": "BRIDGE",
},
  "cpus": "4",
  "mem": "512",
  "uris": ["path to dockercfg.tar.gz"],
  "command" : "./command-to-execute"
}

The Docker Image to run has ENTRYPOINT specified in the dockerfile. So technically, the ENTRYPOINT should run when the docker runs the container. With the way Chronos is set up, I am forced to provide "command" option in the job JSON (skipping command throws back error). Wth command option specified, When the container is actually scheduled on the target node then instead of using the ENTRYPOINT from the dockerfile, it actually tries to run the command specified in the job definition JSON. Can someone provide a way for using Chronos to run dockerfile ENTRYPOINT instead of the command?

Notes: 
Setting command to blank doesn't help.
ENTRYPOINT can be specified as a command in JSON job definition. But don't have access to ENTRYPOINT for all the containers.

**2. How to specify port mappings?:**
Is there any solution to specify port-mapping for the docker with Chronos setup?

**Comment by bengunter** [comment]
@rphull I forked 2.4.0 and added port mapping support.

https://github.com/mesos/chronos/pull/615

**Comment by demobox** [comment]
Run into this as well. Would it be worth considering aligning the semantics here with Marathon, where it's actually now **forbidden** to pass both `cmd` and `args` in the same [app definition](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps)?

```
This args field may be used in place of cmd even when using the default command executor. This change mirrors API and semantics changes in the Mesos CommandInfo protobuf message starting with version 0.20.0. Either cmd or args must be supplied. It is invalid to supply both cmd and args in the same app.
```

**Comment by gazal-k** [comment]
I ran into this issue as well. Setting blank string, `"command":""`, worked for me, for now.
There is another problem though, I'm running a java application and no matter how the application finishes execution, chronos reports the last execution status "SUCCESS". How can we set a failure status if the application doesn't finish correctly?

**Comment by rdigiorgio** [comment]
I'm bumping this at is seems to not be fixed for 3.0.0. Using a Docker image with an entrypoint is really, really hard and you have to play with command and args to make it work. :)

**Comment by mindscratch** [comment]
I concur with @rdigiorgio, I was able to run a container that had arguments and `"command": ""`
