### ISSUE TITLE
post to chronos endpoint fails if command field isn't specified

### ISSUE THREAD

**Issue by tony-kerz** [mesos/chronos#552]
here's what i got from `curl`:
```
curl -L -H 'Content-Type: application/json' -X POST -d@hgbot-redis-backup.chronos.json chronos-32728-s4.marathon.mesos.:10001/scheduler/iso8601
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /scheduler/iso8601. Reason:
<pre>    Server Error</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
```
here's what i got in `stdout` of the job running chronos (this is running on dcos which creates chronos task on marathon which provides access to `stdout` of job):
```
[2015-09-16 01:19:42,656] ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container (com.sun.jersey.spi.container.ContainerResponse:419)
java.lang.NullPointerException
    at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:29)
    at org.apache.mesos.chronos.utils.JobDeserializer.deserialize(JobDeserializer.scala:21)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:800)
    at mesosphere.chaos.validation.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:59)
    at com.sun.jersey.spi.container.ContainerRequest.getEntity(ContainerRequest.java:490)
    at com.sun.jersey.server.impl.model.method.dispatch.EntityParamDispatchProvider$EntityInjectable.getValue(EntityParamDispatchProvider.java:123)
    at com.sun.jersey.server.impl.inject.InjectableValuesProvider.getInjectableValues(InjectableValuesProvider.java:86)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$EntityParamInInvoker.getParams(AbstractResourceMethodDispatchProvider.java:153)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:203)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
```

was able to get past this error by specifying a blank `command` field like so:

```
  "command": " ",
```

**Comment by bobrik** [comment]
#544 describes the same thing.

**Comment by gkleiman** [comment]
Duplicated of $544
