### ISSUE TITLE
docker build fails tests

### ISSUE THREAD

**Issue by tony-kerz** [mesos/chronos#570]
currently running `docker build` against `master` will fail due to failing maven tests

```
SerializerAndDeserializer should::serialize and deserialize a ScheduleBasedJob correctly(org.apache.mesos.chronos.scheduler.api.SerDeTest)  Time elapsed: 0.115 sec  <<< FAILURE!
org.specs2.reporter.JUnitReporter$$anon$1: 'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))'
 is not equal to 
'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>
	at org.apache.mesos.chronos.scheduler.api.SerDeTest$$anonfun$1$$anonfun$apply$4.apply(SerDeTest.scala:96)
	at org.apache.mesos.chronos.scheduler.api.SerDeTest$$anonfun$1$$anonfun$apply$4.apply(SerDeTest.scala:57)


Results :

Failed tests: 
   'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))'
 is not equal to 
'DependencyBasedJob(Set(B, C, D, E),A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test dependency-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RO)), Volume(None,container/dir,None)),ListBuffer(),BRIDGE,false),ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),false,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>
   'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))'
 is not equal to 
'ScheduleBasedJob(FOO/BAR/BAM,A,noop,PT5M,10,20,fooexec,fooflags,7,foo@bar.com,Foo,Test schedule-based job,TODAY,YESTERDAY,true,0.0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List(EqualsConstraint(rack,rack-1), LikeConstraint(rack,rack-[1-3])))' expected:<...AY,YESTERDAY,true,0.[0,0.0,0.0,false,0,List(),false,,DockerContainer(dockerImage,List(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,List(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,List(-testOne),true,false,List](EqualsConstraint(ra...> but was:<...AY,YESTERDAY,true,0.[1,256.0,128.0,false,0,ListBuffer(),false,,DockerContainer(dockerImage,ListBuffer(Volume(Some(/host/dir),container/dir,Some(RW)), Volume(None,container/dir,None)),ListBuffer(),HOST,true),,ListBuffer(EnvironmentVariable(FOO,BAR), EnvironmentVariable(AAAA,BBBB)),true,ListBuffer(-testOne),true,false,ListBuffer](EqualsConstraint(ra...>

Tests run: 76, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:17.406s
[INFO] Finished at: Tue Sep 29 02:50:49 UTC 2015
[INFO] Final Memory: 19M/194M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project chronos: There are test failures.
[ERROR] 
[ERROR] Please refer to /chronos/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2015/09/29 02:50:49 The command [/bin/sh -c mvn clean package] returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by gkleiman** [comment]
They passed for me, so it looks like the tests are flaky.

**Comment by tony-kerz** [comment]
mmm, i'll try again. wonder if there is something non-deterministic about the build (e.g. versions of things, etc)

**Comment by tony-kerz** [comment]
drat, consistently fails for me with same errors. curious what the diff is...

@gkleiman, does it ever fail for you?

i'm running like this:
```
~/g/chronos (tk/hostname) $ docker build --rm -t tonykerz/chronos .
```

i'm running on a macbook via docker-machine:
```
~/g/chronos (tk/hostname) $ docker-machine --version
docker-machine version 0.4.1 (e2c88d6)
```

**Comment by tony-kerz** [comment]
ah, this looks like the same thing: https://github.com/mesos/chronos/issues/558

**Comment by gkleiman** [comment]
The tests pass for me:

```
[gaston@Gastons-MacBook-Pro chronos (master)]$ docker-machine --version
docker-machine version 0.4.1 (HEAD)
[gaston@Gastons-MacBook-Pro chronos (master)]$ docker build --rm .
Sending build context to Docker daemon  48.4 MB
Step 0 : FROM ubuntu:14.04
 ---> 91e54dfb1179
Step 1 : RUN echo "deb http://repos.mesosphere.io/ubuntu/ trusty main" > /etc/apt/sources.list.d/mesosphere.list &&     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF &&     apt-get update &&     apt-get install -y maven     npm     default-jdk     mesos     scala     curl &&     apt-get clean all &&     ln -s /usr/bin/nodejs /usr/bin/node
 ---> Using cache
 ---> c08764785e81
Step 2 : ADD . /chronos
 ---> 7288f9b89258
Removing intermediate container 955948828ce0
Step 3 : WORKDIR /chronos
 ---> Running in 408c44cb0dfa
 ---> 1dcdfadb184f
Removing intermediate container 408c44cb0dfa
Step 4 : RUN mvn clean package
 ---> Running in d8fe9b690dc5
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building chronos 2.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 6.3 KB/sec)

[...]

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

[...]

Results :

Tests run: 76, Failures: 0, Errors: 0, Skipped: 0

[...]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:21.615s
[INFO] Finished at: Mon Oct 12 10:28:54 UTC 2015
[INFO] Final Memory: 21M/145M
[INFO] ------------------------------------------------------------------------
 ---> afe1ac4bec94
Removing intermediate container d8fe9b690dc5
Step 5 : EXPOSE 8080
 ---> Running in a62a49647ebf
 ---> f1d209a62e84
Removing intermediate container a62a49647ebf
Step 6 : ENTRYPOINT bin/start-chronos.bash
 ---> Running in 446e2519100f
 ---> 064f20b3c0e8
Removing intermediate container 446e2519100f
Successfully built 064f20b3c0e8
[gaston@Gastons-MacBook-Pro chronos (master)]$ docker-machine --version
docker-machine version 0.4.1 (HEAD)
[gaston@Gastons-MacBook-Pro chronos (master)]$
```

The link in #558 is broken, so if you see the test fail again, it would be very useful if you can include the full test logs.

**Comment by developerSid** [comment]
I am having the same issue while trying to setup a build for deploying to an ubuntu system.  As part of that I was running the building using the Dockerfile for version 2.4.0 of Chronos.

The Docker build was executed from an Ubuntu 15.10 VM running in VMWare Workstation on a Windows 8.1 desktop.  I've attached the build output.  Hope this helps.
[chronos-build-failure.txt](https://github.com/mesos/chronos/files/104108/chronos-build-failure.txt)

**Comment by noedetore** [comment]
having same issue
