### ISSUE TITLE
chronos crash - curator/zk issue?

### ISSUE THREAD

**Issue by flyinprogrammer** [mesos/chronos#590]
``` log
Nov 16 15:03:07 ashmes004 chronos[22886]: [2015-11-16 15:03:07,459] ERROR Background exception was not retry-able or retry gave up (org.apache.curator.framework.imps.CuratorFrameworkImpl:543)
Nov 16 15:03:07 ashmes004 chronos[22886]: java.lang.IllegalArgumentException: Path must start with / character
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:53)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.utils.ZKPaths.getNodeFromPath(ZKPaths.java:56)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:523)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.recipes.leader.LeaderLatch.access$700(LeaderLatch.java:62)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.recipes.leader.LeaderLatch$7.processResult(LeaderLatch.java:581)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:715)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:502)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)
Nov 16 15:03:07 ashmes004 chronos[22886]: at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

Anyone ever see these? it just happened on every chronos node i have lol

**Comment by flyinprogrammer** [comment]
https://github.com/HubSpot/Singularity/issues/620 

Maybe this is related?

**Comment by kolloch** [comment]
Hi @flyinprogrammer, does it happen regularly and than disappear after your restart Chronos? What options dod you start Chronos with?
