### ISSUE TITLE
Starting chronos:v3.0.0 with framework auth failed

### ISSUE THREAD

**Issue by koboltmarky** [mesos/chronos#759]
Hi,

i'm trying to start chronos:v3.0.0 as a service on dcos 1.8.4 and mesos 1.0.1. I enabled the framework authentication and start the chronos service with:

```
 "--mesos_authentication_principal",
    "chronos",
    "--mesos_authentication_secret_file",
    "/etc/chronos.pw"
```

I'm always getting the following error:

```
I1212 14:56:57.786523    73 zookeeper.cpp:259] A new leading master (UPID=master@XXX:5050) is detected
I1212 14:56:57.786602    73 sched.cpp:330] New master detected at master@XXX:5050
I1212 14:56:57.786793    73 sched.cpp:396] Authenticating with master master@XXX:5050
I1212 14:56:57.786804    73 sched.cpp:403] Using default CRAM-MD5 authenticatee
I1212 14:56:57.787107    69 authenticatee.cpp:97] Initializing client SASL
I1212 14:56:57.789608    69 authenticatee.cpp:121] Creating new client SASL connection
I1212 14:56:57.794262    73 authenticatee.cpp:213] Received SASL authentication mechanisms: CRAM-MD5
I1212 14:56:57.794291    73 authenticatee.cpp:239] Attempting to authenticate with mechanism 'CRAM-MD5'
I1212 14:56:57.795130    73 authenticatee.cpp:259] Received SASL authentication step
E1212 14:56:57.796017    55 sched.cpp:496] Master master@XXXX:5050 refused authentication
I1212 14:56:57.796032    55 sched.cpp:1171] Got error 'Master refused authentication'
I1212 14:56:57.796036    55 sched.cpp:2021] Asked to abort the driver
I1212 14:56:57.800017   117 sched.cpp:1987] Asked to stop the driver
Exception in thread "JobScheduler STOPPING" java.lang.IllegalStateException: Already closed or has not been started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.close(LeaderLatch.java:202)
	at org.apache.mesos.chronos.scheduler.jobs.JobScheduler.shutDown(JobScheduler.scala:607)
	at com.google.common.util.concurrent.AbstractIdleService$2$2.run(AbstractIdleService.java:69)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:745)
```

Can i use the framework authentication with chronos v3.0.0 ?

Greets
Marc

**Comment by brndnmtthws** [comment]
Which version of Mesos?

**Comment by koboltmarky** [comment]
Version:1.0.1

**Comment by brndnmtthws** [comment]
Nothing really changed in 3.0.0 regarding auth, but nonetheless I'll look into it. Thanks for reporting.

**Comment by brndnmtthws** [comment]
Is this still a problem for you? I don't see anything that indicates a problem. Is it possible that the credentials are wrong?

**Comment by koboltmarky** [comment]
I double checked the passwords, but the problem still exists.

**Comment by brndnmtthws** [comment]
It looks pretty similar to https://github.com/mesosphere/marathon/issues/3331. Can you take a look at that issue and see if it's the same?

**Comment by koboltmarky** [comment]
We're using marathon with framework security in the same setup, that works. The newline issue i have doubled checked

**Comment by sdouglasnelson** [comment]
I'm getting similar errors. I'm not running dcos and I also tried the same with version v3.0.1. This is my docker run command:
```
docker run --net=host -e PORT0=4440 -e PORT1=4441 -e SSL_ENABLED=true \
-e SSL_KEY_FILE=/etc/mesos/ssl/mesos.key -e SSL_CERT_FILE=/etc/mesos/ssl/mesos.pem \
--name chronos -p 4440:4440 -p 4441:4441 -v /etc/chronos:/etc/chronos \
-v /etc/mesos/ssl:/etc/mesos/ssl mesosphere/chronos:v3.0.0 \
--zk_hosts=ip1:2181,ip2:2181,ip3:2181 --master=zk://ip1:2181,ip2:2181,ip3:2181/mesos \
--hostname=hostname1 --mesos_framework_name=chronos \
--http_credentials=cuser:cpass --disable_http --https_port=4440 \
--mesos_authentication_principal=muser --ssl_keystore_password=mkeypass \
--mesos_authentication_secret_file=/etc/chronos/auth/mesos.secret \
--ssl_keystore_path=/etc/chronos/ssl/chronos.jks
```

**Comment by rohte** [comment]
Similar problem for me. Running Mesos 1.1.0 and Chronos 3.0.1. Same setup works fine with Chronos 2.4.0

Interesting observation: When I leave out the `--mesos_authentication_secret_file` flag, chronos doesn't start, but when I give it a non-existent file, it starts up fine but all scheduled jobs remain in 'queuing' state

arguments for chronos are:
```
--master zk://1.2.3.4:2181,2.3.4.5:2181/mesos --zk_hosts 1.2.3.4:2181,2.3.4.5:2181 
--zk_path /env/chronos --mesos_role chronos --user chronos 
--hostname this.host.example.com --http_port 8081 --http_address 127.0.0.1 
--mesos_checkpoint  --revive_offers_for_new_jobs  --decline_offer_duration 600000 
--webui_url http://chronos.env.example.com/ --mesos_framework_name chronos.env 
--mesos_authentication_principal chronos 
--mesos_authentication_secret_file /path/secret_file
```

**Comment by mcoffin** [comment]
I'm seeing this same issue.

| Component | Version |
| --------- | ------- |
| Mesos | `1.1.0` |
| Chronos | `v3.0.1` |

Here is my marathon config for running chronos (ignore the fact that I'm re-using my marathon credential for authentication, that's temporary.

```json
{
  "id": "/chronos",
  "cpus": 0.3,
  "mem": 1024,
  "disk": 0,
  "instances": 0,
  "container": {
    "type": "MESOS",
    "docker": {
      "image": "mesosphere/chronos:v3.0.1"
    }
  },
  "ipAddress": {
      "networkName": "calico-net-1"
  },
  "env": {
    "LIBPROCESS_SSL_SUPPORT_DOWNGRADE": "false",
    "LIBPROCESS_SSL_KEY_FILE": "master.key",
    "MESOS_NATIVE_JAVA_LIBRARY": "/usr/lib/libmesos-1.0.1.so",
    "PORT1": "8081",
    "LIBPROCESS_SSL_CERT_FILE": "master.crt",
    "LIBPROCESS_SSL_ENABLED": "true",
    "PORT0": "8080"
  },
  "uris": [
    "file:///etc/mesos/master.key",
    "file:////etc/mesos/master.crt",
    "file:///etc/mesos/secrets/marathon.secret"
  ],
  "args": [
    "--zk_hosts",
    "master0:2181",
    "--master",
    "zk://master0:2181/mesos",
    "--mesos_authentication_principal",
    "marathon",
    "--mesos_authentication_secret_file",
    "marathon.secret"
  ]
}
```

**Comment by liangyanfeng** [comment]
In  source code  src/main/scala/org/apache/mesos/chronos/scheduler/mesos/SchedulerDriverBuilder.scala,
we should use credentialBuilder.setSecretBytes(secretBytes) instead of credentialBuilder.setSecret(secretBytes.toString).

**Comment by fortune-juggle** [comment]
this will not help @liangyanfeng
same problem here: testet with your suggestion, too 
## version
chronos: mesosphere/chronos:latest
mesos: 1.1.0-2.0.107.ubuntu1404
marathon: 1.3.6-1.0.540.ubuntu1404 

### config.json
```
{
  "id": "/szops/chronos",
  "cmd": null,
  "cpus": 0.3,
  "mem": 1024,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
   "volumes": [
      {
        "containerPath": "/etc/mesos/here_be_credentials",
        "hostPath": "/etc/mesos/here_be_credentials",
        "mode": "RW"
      },
      {
        "containerPath": "/etc/chronos/chronos.jks",
        "hostPath": "/etc/chronos/chronos.jks",
        "mode": "RW"
      }
  ],
    "docker": {
      "image": "mesosphere/chronos:latest",
      "network": "HOST",
      "portMappings": null,
      "privileged": false,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "env": {
    "PORT1": "4400",
    "PORT0": "4430"
  },
  "healthChecks": [
   {
    "path": "/",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 30,
    "maxConsecutiveFailures": 3,
    "ignoreHttp1xx": false
   }
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "uris": [
    "file:///etc/mesos/here_be_credentials",
    "file:///etc/chronos/chronos.jks"
  ],
  "args": [
    "--master=zk://zookeeper2:2181,zookeeper1:2181,zookeeper3:2181/$cluster_name",
    "--http_credentials=$user:$pass",
    "--disable_after_failures=5",
    "--zk_hosts=zookeeper2:2181,zookeeper1:2181,zookeeper3:2181",
    "--mesos_authentication_principal=chronos",
    "--ssl_keystore_password=$pass",
    "--ssl_keystore_path=/etc/chronos/chronos.jks"
    "--mesos_authentication_secret_file=/path/to/credentials",
    "--webui_url=https://chronos.example.com/"
  ]
  ],
  "backoffSeconds": 10,
  "backoffFactor": 2,
  "maxLaunchDelaySeconds": 360000
}
```
Argument "--ssl_keystore_path=/etc/chronos/chronos.jks" is not readable for chronos.
as well as  "/etc/mesos/here_be_credentials" .Same Error ```[Thread-11] ERROR org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework - Master refused authentication``` .

**Comment by brndnmtthws** [comment]
Please try the `mesosphere/chronos:set-auth-params-as-bytes` image from #802.

**Comment by fortune-juggle** [comment]
thanks i will do that

**Comment by fortune-juggle** [comment]
sorry no luck 
```
2017-02-15 18:04:38,152:1(0x7fb9051c7700):ZOO_INFO@check_events@1728: initiated connection to server [10.0.42.26:2181]
2017-02-15 18:04:38,155:1(0x7fb9051c7700):ZOO_INFO@check_events@1775: session establishment complete on server [10.0.42.26:2181], sessionId=0x15a37a6946334b9, negotiated timeout=10000
I0215 18:04:38.155341    20 group.cpp:349] Group process (group(1)@10.0.42.44:4400) connected to ZooKeeper
I0215 18:04:38.155400    20 group.cpp:837] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0215 18:04:38.155493    20 group.cpp:427] Trying to create path '/beta_twiri' in ZooKeeper
I0215 18:04:38.157490    20 detector.cpp:152] Detected a new leader: (id='366')
I0215 18:04:38.157703    21 group.cpp:706] Trying to get '/beta_twiri/json.info_0000000366' in ZooKeeper
I0215 18:04:38.158673    21 zookeeper.cpp:259] A new leading master (UPID=master@10.0.42.46:5050) is detected
I0215 18:04:38.159106    21 sched.cpp:330] New master detected at master@10.0.42.46:5050
I0215 18:04:38.159368    21 sched.cpp:396] Authenticating with master master@10.0.42.46:5050
I0215 18:04:38.159391    21 sched.cpp:403] Using default CRAM-MD5 authenticatee
I0215 18:04:38.159762    21 authenticatee.cpp:97] Initializing client SASL
I0215 18:04:38.164099    21 authenticatee.cpp:121] Creating new client SASL connection
I0215 18:04:38.165813    19 authenticatee.cpp:213] Received SASL authentication mechanisms: CRAM-MD5
I0215 18:04:38.165856    19 authenticatee.cpp:239] Attempting to authenticate with mechanism 'CRAM-MD5'
I0215 18:04:38.167196    23 authenticatee.cpp:259] Received SASL authentication step
E0215 18:04:38.168294    24 sched.cpp:496] Master master@10.0.42.46:5050 refused authentication
I0215 18:04:38.168438    24 sched.cpp:1171] Got error 'Master refused authentication'
I0215 18:04:38.168553    24 sched.cpp:2021] Asked to abort the driver
I0215 18:04:38.173658    58 sched.cpp:1987] Asked to stop the driver
Exception in thread "JobScheduler STOPPING" java.lang.IllegalStateException: Already closed or has not been started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.close(LeaderLatch.java:202)
	at org.apache.mesos.chronos.scheduler.jobs.JobScheduler.shutDown(JobScheduler.scala:670)
	at com.google.common.util.concurrent.AbstractIdleService$2$2.run(AbstractIdleService.java:69)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:745)
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
```

**Comment by fortune-juggle** [comment]
hi @brndnmtthws ,
I have repeated all the steps with a clear head. And we can go with it.
I have build a new container with your changes, because I could not find the image.
Everything works well. Thanks for your great work.

```
INFO org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
```

**Comment by koboltmarky** [comment]
mesosphere/chronos:set-auth-params-as-bytes also works for me
