### ISSUE TITLE
After upgrade Chronos can not register on Mesos

### ISSUE THREAD

**Issue by nihn** [mesos/chronos#771]
Hello,

I've upgraded Chronos to 3.0.1 and after that it is no longer able to register itself on Mesos master. Process run normally, WebUI is available and tasks visible however most of them is in the "queued" state.

After startup there is one error in Chronos log which seems to be responsible:
```
Dec 29 11:17:25 m2 chronos[10728]: 11:17:25.306 [pool-5-thread-1] ERROR org.apache.curator.framework.listen.ListenerCon
Dec 29 11:17:25 m2 chronos[10728]: java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
Dec 29 11:17:25 m2 chronos[10728]: at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
Dec 29 11:17:25 m2 chronos[10728]: at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
Dec 29 11:17:25 m2 chronos[10728]: at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
Dec 29 11:17:25 m2 chronos[10728]: at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
Dec 29 11:17:25 m2 chronos[10728]: at scala.concurrent.Await$.result(package.scala:190)
Dec 29 11:17:25 m2 chronos[10728]: at mesosphere.mesos.util.FrameworkIdUtil.fetch(FrameworkIdUtil.scala:40)
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.mesos.chronos.scheduler.mesos.MesosDriverFactory.makeDriver(MesosDrive
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.mesos.chronos.scheduler.mesos.MesosDriverFactory.get(MesosDriverFactor
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.mesos.chronos.scheduler.mesos.MesosDriverFactory.start(MesosDriverFact
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.mesos.chronos.scheduler.jobs.JobScheduler.onElected(JobScheduler.scala
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.mesos.chronos.scheduler.jobs.JobScheduler$$anon$3.isLeader(JobSchedule
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:
Dec 29 11:17:25 m2 chronos[10728]: at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.jav
Dec 29 11:17:25 m2 chronos[10728]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Dec 29 11:17:25 m2 chronos[10728]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Dec 29 11:17:25 m2 chronos[10728]: at java.lang.Thread.run(Thread.java:745)
```
I've checked Mesos logs and there is nothing so it does not seem that Chronos even try to connect to it.

Mesos configuration:
version 1.0.1
ssl enabled
authentication enabled

**Comment by nihn** [comment]
It seems that request to master timed out to early, increasing `--zk_timeout` fixed this.
