### ISSUE TITLE
Chronos immediately dies when hostname is not dns-resolvable

### ISSUE THREAD

**Issue by matt-deboer** [mesos/chronos#801]
As you can see from the below stack-trace, when chronos can't resolve the hostname of the agent on which it runs, it cannot recover.

Maybe it could fall back to using the value of `$LIBPROCESS_IP` or `$HOST` or allow an override?

Context: this occurrs on Chronos 3.0.1, in a cluster where the agents are registered with IP addresses (no resolvable dns names), and vpc dns doesn't resolve the aws internal hostnames.

```
Exception in thread "main" java.net.UnknownHostException: ip-10-253-144-68.example.org: ip-10-253-144-68.example.org: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.apache.mesos.chronos.scheduler.config.SchedulerConfiguration$$anonfun$hostname$1.apply(SchedulerConfiguration.scala:39)
	at org.apache.mesos.chronos.scheduler.config.SchedulerConfiguration$$anonfun$hostname$1.apply(SchedulerConfiguration.scala:39)
	at org.rogach.scallop.Scallop$$anonfun$get$5$$anonfun$apply$33.apply(Scallop.scala:584)
	at org.rogach.scallop.Scallop$$anonfun$get$5$$anonfun$apply$33.apply(Scallop.scala:584)
	at scala.Option.orElse(Option.scala:289)
	at org.rogach.scallop.Scallop$$anonfun$get$5.apply(Scallop.scala:584)
	at org.rogach.scallop.Scallop$$anonfun$get$5.apply(Scallop.scala:578)
	at scala.Option.map(Option.scala:146)
	at org.rogach.scallop.Scallop.get(Scallop.scala:578)
	at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:664)
	at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:655)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.rogach.scallop.Scallop.verify(Scallop.scala:655)
	at org.rogach.scallop.ScallopConf.verifyBuilder(ScallopConf.scala:343)
	at org.rogach.scallop.ScallopConf.verify(ScallopConf.scala:587)
	at org.apache.mesos.chronos.scheduler.Main$.delayedEndpoint$org$apache$mesos$chronos$scheduler$Main$1(Main.scala:27)
	at org.apache.mesos.chronos.scheduler.Main$delayedInit$body.apply(Main.scala:21)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.apache.mesos.chronos.scheduler.Main$.main(Main.scala:21)
	at org.apache.mesos.chronos.scheduler.Main.main(Main.scala)
Caused by: java.net.UnknownHostException: ip-10-253-144-68.example.org: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 26 more
```

**Comment by brndnmtthws** [comment]
Try using a hostname that can be resolved. Pass a valid hostname, which could be an IP in your case, with the `--hostname` argument.

**Comment by matt-deboer** [comment]
That works, thanks.
(Adding `--hostname $HOST` to the args list, which I believe used to be part of the default configuration for chronos v2, FYI)
